name: Deploy cf-pages (svc) from stage only when needed

on:
  schedule:
    - cron: '0 15,17,19,21,23,1,3,5,7,9,11,13 * * *'
  workflow_dispatch: {}

jobs:
  merge-to-cf-pages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Merge main into cf-pages branch
      run: |
        git fetch origin
        git checkout cf-pages || git checkout -b cf-pages origin/cf-pages
        
        git merge main -m "Merge main into cf-pages for deployment"
        git push origin cf-pages
