name: Deploy to stage by main push

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'
      
jobs:
  build-and-deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Deploy to stage branch
      run: |
        git fetch origin stage
        git switch stage || git checkout -b stage
        
        git rm -rf .
        
        git checkout main -- public
        mv public/* .
        rm -rf public
        
        git add .
        git commit -m "Deploy site from main/public to stage"
        git push origin stage --force